@startuml
hide stereotype
skinparam DefaultFontName "Roboto"
skinparam BackgroundColor transparent
skinparam Shadowing false
skinparam Handwritten false

skinparam Note {
    BorderColor                 #c6c496
    BackgroundColor             #fcf499
    FontSize                    12
}

skinparam Sequence {
    TitleFontSize               12
    TitleFontColor              #606060
    ArrowColor                  #303030
    DividerBackgroundColor      #EEEEEE
    GroupBackgroundColor        #EEEEEE
    LifeLineBackgroundColor     white
    LifeLineBorderColor         #303030
    ParticipantBackgroundColor  #FEFEFE
    ParticipantBorderColor      #303030
    BoxLineColor                #303030
    BoxBackgroundColor          #DDDDDD
}

skinparam Title {
    FontSize                    12
    FontColor                   #606060
}

skinparam Activity {
    StartColor                  #a6a955
    EndColor                    #983132
    ArrowColor                  #303030
    ArrowFontSize               10
    BarColor                    #F0A0A0
    BorderColor                 transparent
    BackgroundColor             #DEEEFE
    DiamondBackgroundColor      #febd12
    DiamondBorderColor          transparent
}

skinparam State {
    StartColor                   #303030
    EndColor                     #303030
    BackgroundColor              #FEFEFE
    BackgroundColor<<Failure>>   #FEA0A0
    BackgroundColor<<Success>>   #A0FEA0
    BorderColor                  #303030
    ArrowColor                   #606060
    FontStyle                    bold
}

skinparam Object {
    BackgroundColor<<HUB>>       #bbdcf7
    BorderColor<<HUB>>           #1670b9
    BackgroundColor<<LNK>>       #f4bdc0
    BorderColor<<LNK>>           #bf2026
    BackgroundColor<<SAT>>       #feebb3
    BorderColor<<SAT>>           #faba02
    BackgroundColor<<LSAT>>      #9bbb58
    BorderColor<<LSAT>>          #637b32
    BackgroundColor<<LSAT>>      #dee9c9
    BackgroundColor              #FEFEFE
    BorderColor                  #303030
    FontStyle                    normal
    FontSize                     14

}

skinparam Class {
    BackgroundColor<<HUB>>       #bbdcf7
    BorderColor<<HUB>>           #1670b9
    BackgroundColor<<LNK>>       #f4bdc0
    BorderColor<<LNK>>           #bf2026
    BackgroundColor<<SAT>>       #feebb3
    BorderColor<<SAT>>           #faba02
    BackgroundColor<<LSAT>>      #9bbb58
    BorderColor<<LSAT>>          #637b32
    BackgroundColor<<LSAT>>      #dee9c9
    FontStyle                    normal
    FontSize                     14
}

skinparam Package {
    BorderThickness              1
}

@enduml
