@startuml
!include includes/datavault-defines.wsd

title Student Logical Model\n

'Who        People and Organizations        Customer, Student
'What       Things                          Product, Service
'When       Date                            EffectiveDate, InvoiceDate (Normally in a Satellite of the How and Why)
'Where      Locations                       Store, Branch, BillingAddress, ShippingAddress (Normally Address is a Satellite of Who and Linked to How)
'Why        Reasons and Causality           Weather, 
'How        Sale, Quote, Event              SalesOrder, WorkOrder, Application (This is normally follow Header - Line pattern with Keyed instances)
'How Many   Measures and KPIs               Normally in the Satellite of the How

object Award <<HUB>>
object Organization <<HUB>>
object Researcher <<HUB>>
object Anzsrc <<HUB>>
object Resources <<HUB>>
object ResourceTypes <<HUB>>
object Application <<LNK>>
object Applicant <<HUB>>
object Recipient <<HUB>>
object Project
object AwardGranted <<LNK>>
object AwardResources <<LNK>>
'object Contract

Application <- Applicant : Makes an 
Applicant --> AwardGranted
AwardGranted --> Award 
AwardGranted --> Recipient : Is awarded to
AwardGranted <- Researcher : Doing the work
Award --> Project
Organization -> AwardGranted
AwardResources --> Award
AwardResources --> Resources
Resources --> ResourceTypes
Anzsrc -> Application
Anzsrc --> AwardGranted


@enduml
